package Sistema;

import DTO.LoginDTO;
import dao.ConexaoDAO;
import dao.LoginDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import java.sql.Connection;

public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        ConexaoDAO conexaoDAO = new ConexaoDAO();
        Connection conectaBD = conexaoDAO.conectaBD();
        System.out.println(conectaBD);
        if (conectaBD != null) {
            txtStatus_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dbok.png")));
        } else {
            txtStatus_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/derror.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin_Entrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtLogin_Usuario = new javax.swing.JTextField();
        txtLogin_Senha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin_Cadastrar = new javax.swing.JButton();
        rdbVisualizar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtStatus_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System - Controle Financeiro  - Version 1.0.1");
        setResizable(false);

        btnLogin_Entrar.setBackground(new java.awt.Color(102, 102, 102));
        btnLogin_Entrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLogin_Entrar.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin_Entrar.setText("ENTRAR");
        btnLogin_Entrar.setToolTipText("");
        btnLogin_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin_EntrarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user_1077012.png"))); // NOI18N
        jLabel2.setText("Usuario");

        txtLogin_Usuario.setBackground(new java.awt.Color(102, 102, 102));
        txtLogin_Usuario.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtLogin_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogin_UsuarioActionPerformed(evt);
            }
        });

        txtLogin_Senha.setBackground(new java.awt.Color(102, 102, 102));
        txtLogin_Senha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/budget_781760.png"))); // NOI18N
        jLabel3.setText("  SISTEMA DE CONTROLE FINANCEIRO");

        btnLogin_Cadastrar.setBackground(new java.awt.Color(102, 102, 102));
        btnLogin_Cadastrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLogin_Cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin_Cadastrar.setText("CADASTRAR");
        btnLogin_Cadastrar.setToolTipText("");
        btnLogin_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin_CadastrarActionPerformed(evt);
            }
        });

        rdbVisualizar.setText("Exibir Senha");
        rdbVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbVisualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/password_12795740.png"))); // NOI18N
        jLabel1.setText("Senha");

        txtStatus_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dberror.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtStatus_Login)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnLogin_Entrar))
                    .addComponent(txtLogin_Senha)
                    .addComponent(txtLogin_Usuario))
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogin_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLogin_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbVisualizar)
                    .addComponent(btnLogin_Entrar))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin_Cadastrar)
                    .addComponent(txtStatus_Login))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(616, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin_EntrarActionPerformed

        try {
            String Login_Usuario, Login_Senha;

            Login_Usuario = txtLogin_Usuario.getText();
            Login_Senha = txtLogin_Senha.getText();

            LoginDTO objlogindto = new LoginDTO();
            objlogindto.setLogin_Usuario(Login_Usuario);
            objlogindto.setLogin_Senha(Login_Senha);

            LoginDAO objlogindao = new LoginDAO();
            ResultSet rslogindao = objlogindao.autenticacaoLogin(objlogindto);

            if (rslogindao.next()) {
                //chamar tela que eu quero abrir
                HomeView objhomeview = new HomeView();
                objhomeview.setVisible(true);

                dispose();

            } else {
                //enviar mensagem dizendo incorreto
                JOptionPane.showMessageDialog(null, "Usuario ou Senha Inválida");

            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro em LoginView" + error);
        }


    }//GEN-LAST:event_btnLogin_EntrarActionPerformed

    private void txtLogin_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogin_UsuarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtLogin_UsuarioActionPerformed

    private void btnLogin_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin_CadastrarActionPerformed
        // TODO add your handling code here:
        CadastroView objcadastroview = new CadastroView();
        objcadastroview.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnLogin_CadastrarActionPerformed

    private void rdbVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbVisualizarActionPerformed
        // TODO add your handling code here:
        ExibirSenha(txtLogin_Senha, rdbVisualizar);
    }//GEN-LAST:event_rdbVisualizarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    public void ExibirSenha(JPasswordField txtCadastrar_Senha, JRadioButton rdbVisualizar) {
        // Adiciona a ação ao botão de visualização
        rdbVisualizar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                txtCadastrar_Senha.setEchoChar(rdbVisualizar.isSelected() ? '\u0000' : '*');
            }
        });

        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin_Cadastrar;
    private javax.swing.JButton btnLogin_Entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rdbVisualizar;
    private javax.swing.JPasswordField txtLogin_Senha;
    private javax.swing.JTextField txtLogin_Usuario;
    private javax.swing.JLabel txtStatus_Login;
    // End of variables declaration//GEN-END:variables
}
