/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sistema;

import dao.Registro_Fevereiro_2024DAO;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.JTextField;

public class RegistroView extends javax.swing.JFrame {

    private Registro_Janeiro_2024View registroView;

    /**
     * Creates new form CadastroView
     */
    public RegistroView() {
        initComponents();
        registroView = new Registro_Janeiro_2024View();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnHome_Registro = new javax.swing.JButton();
        btnHome_RendaMensal = new javax.swing.JButton();
        btn_Home_TelaInicial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnRegistro_Maio = new javax.swing.JButton();
        btnRegistro_Agosto = new javax.swing.JButton();
        btnRegistro_Setembro = new javax.swing.JButton();
        btnRegistro_Outubro = new javax.swing.JButton();
        btnRegistro_Janeiro = new javax.swing.JButton();
        btnRegistro_Novembro = new javax.swing.JButton();
        btnRegistro_Fevereiro = new javax.swing.JButton();
        btnRegistro_Junho = new javax.swing.JButton();
        btnRegistro_Abril = new javax.swing.JButton();
        btnRegistro_Julho = new javax.swing.JButton();
        btnRegistro_Março = new javax.swing.JButton();
        btnRegistro_Dezembro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHome_Registro.setBackground(new java.awt.Color(255, 255, 255));
        btnHome_Registro.setForeground(new java.awt.Color(0, 0, 0));
        btnHome_Registro.setText("Registro");
        btnHome_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_RegistroActionPerformed(evt);
            }
        });

        btnHome_RendaMensal.setBackground(new java.awt.Color(51, 51, 51));
        btnHome_RendaMensal.setForeground(new java.awt.Color(255, 255, 255));
        btnHome_RendaMensal.setText("Renda Mensal");
        btnHome_RendaMensal.setMaximumSize(new java.awt.Dimension(73, 23));
        btnHome_RendaMensal.setMinimumSize(new java.awt.Dimension(73, 23));
        btnHome_RendaMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome_RendaMensalActionPerformed(evt);
            }
        });

        btn_Home_TelaInicial.setBackground(new java.awt.Color(51, 51, 51));
        btn_Home_TelaInicial.setForeground(new java.awt.Color(255, 255, 255));
        btn_Home_TelaInicial.setText("Home");
        btn_Home_TelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Home_TelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(btnHome_RendaMensal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(btn_Home_TelaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btn_Home_TelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome_RendaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");

        btnRegistro_Maio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Maio.setText("Maio - 2024");
        btnRegistro_Maio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_MaioActionPerformed(evt);
            }
        });

        btnRegistro_Agosto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Agosto.setText("Agosto - 2024");
        btnRegistro_Agosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_AgostoActionPerformed(evt);
            }
        });

        btnRegistro_Setembro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Setembro.setText("Setembro - 2024");
        btnRegistro_Setembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_SetembroActionPerformed(evt);
            }
        });

        btnRegistro_Outubro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Outubro.setText("Outubro - 2024");
        btnRegistro_Outubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_OutubroActionPerformed(evt);
            }
        });

        btnRegistro_Janeiro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Janeiro.setText("Janeiro - 2024");
        btnRegistro_Janeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_JaneiroActionPerformed(evt);
            }
        });

        btnRegistro_Novembro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Novembro.setText("Novembro - 2024");
        btnRegistro_Novembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_NovembroActionPerformed(evt);
            }
        });

        btnRegistro_Fevereiro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Fevereiro.setText("Fevereiro - 2024");
        btnRegistro_Fevereiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_FevereiroActionPerformed(evt);
            }
        });

        btnRegistro_Junho.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Junho.setText("Junho - 2024");
        btnRegistro_Junho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_JunhoActionPerformed(evt);
            }
        });

        btnRegistro_Abril.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Abril.setText("Abril - 2024");
        btnRegistro_Abril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_AbrilActionPerformed(evt);
            }
        });

        btnRegistro_Julho.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Julho.setText("Julho - 2024");
        btnRegistro_Julho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_JulhoActionPerformed(evt);
            }
        });

        btnRegistro_Março.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Março.setText("Março - 2024");
        btnRegistro_Março.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_MarçoActionPerformed(evt);
            }
        });

        btnRegistro_Dezembro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRegistro_Dezembro.setText("Dezembro - 2024");
        btnRegistro_Dezembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistro_DezembroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRegistro_Julho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Junho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Maio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Abril, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Março, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Fevereiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Janeiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Agosto, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRegistro_Novembro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Outubro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Setembro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro_Dezembro, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(675, 675, 675)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnRegistro_Janeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Fevereiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Março)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Abril)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Maio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Junho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Julho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Agosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnRegistro_Setembro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Outubro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Novembro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro_Dezembro)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(718, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHome_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_RegistroActionPerformed
        // chamar tela de registro
        RegistroView objregistroview = new RegistroView();
        objregistroview.setVisible(true);

        dispose();

    }//GEN-LAST:event_btnHome_RegistroActionPerformed

    private void btnHome_RendaMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome_RendaMensalActionPerformed
        // chamar tela de renda mensal
        RendaMensalView objrendamensalview = new RendaMensalView();
        objrendamensalview.setVisible(true);

        dispose();

    }//GEN-LAST:event_btnHome_RendaMensalActionPerformed

    private void btn_Home_TelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Home_TelaInicialActionPerformed
        // chamar tela inicial
        HomeView objhomeviewTelaInicial = new HomeView();
        objhomeviewTelaInicial.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_Home_TelaInicialActionPerformed

    private void btnRegistro_JaneiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_JaneiroActionPerformed
        // chamar registro_janeiro_2024
        Registro_Janeiro_2024View objjaneiro2024 = new Registro_Janeiro_2024View();
        objjaneiro2024.setVisible(true);

        dispose();

    }//GEN-LAST:event_btnRegistro_JaneiroActionPerformed

    private void btnRegistro_FevereiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_FevereiroActionPerformed
        // chamar registro_fevereiro_2024
        Registro_Fevereiro_2024View objfevereiro2024 = new Registro_Fevereiro_2024View();
        objfevereiro2024.setVisible(true);
        
        dispose();

    }//GEN-LAST:event_btnRegistro_FevereiroActionPerformed

    private void btnRegistro_AbrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_AbrilActionPerformed
        // chamar registro_abril_2024
        Registro_Abril_2024View objabril2024 = new Registro_Abril_2024View();
        objabril2024.setVisible(true);

        dispose();

    }//GEN-LAST:event_btnRegistro_AbrilActionPerformed

    private void btnRegistro_MarçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_MarçoActionPerformed
        // chamar registro_março_2024
        Registro_Março_2024View objmarço2024 = new Registro_Março_2024View();
        objmarço2024.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnRegistro_MarçoActionPerformed

    private void btnRegistro_MaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_MaioActionPerformed
        // chamar registro_maio_2024
        Registro_Maio_2024View objmaio2024 = new Registro_Maio_2024View();
        objmaio2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_MaioActionPerformed

    private void btnRegistro_JunhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_JunhoActionPerformed
        // chamar registro_junho_2024
        Registro_Junho_2024View objjunho2024 = new Registro_Junho_2024View();
        objjunho2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_JunhoActionPerformed

    private void btnRegistro_JulhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_JulhoActionPerformed
        // chamar registro_julho_2024
        Registro_Julho_2024View objjulho2024 = new Registro_Julho_2024View();
        objjulho2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_JulhoActionPerformed

    private void btnRegistro_AgostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_AgostoActionPerformed
        // chamar registro_agosto_2024
        Registro_Agosto_2024View objagosto2024 = new Registro_Agosto_2024View();
        objagosto2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_AgostoActionPerformed

    private void btnRegistro_SetembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_SetembroActionPerformed
        // chamar registro_setembro_2024
        Registro_Setembro_2024View objsetembro2024 = new Registro_Setembro_2024View();
        objsetembro2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_SetembroActionPerformed

    private void btnRegistro_OutubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_OutubroActionPerformed
        // chamar registro_novembro_2024
        Registro_Outubro_2024View objoutubro2024 = new Registro_Outubro_2024View();
        objoutubro2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_OutubroActionPerformed

    private void btnRegistro_NovembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_NovembroActionPerformed
        // chamar registro_novembro_2024
        Registro_Novembro_2024View objnovembro2024 = new Registro_Novembro_2024View();
        objnovembro2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_NovembroActionPerformed

    private void btnRegistro_DezembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistro_DezembroActionPerformed
        // chamar registro_dezembro_2024
        Registro_Dezembro_2024View objdezembro2024 = new Registro_Dezembro_2024View();
        objdezembro2024.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistro_DezembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome_Registro;
    private javax.swing.JButton btnHome_RendaMensal;
    private javax.swing.JButton btnRegistro_Abril;
    private javax.swing.JButton btnRegistro_Agosto;
    private javax.swing.JButton btnRegistro_Dezembro;
    private javax.swing.JButton btnRegistro_Fevereiro;
    private javax.swing.JButton btnRegistro_Janeiro;
    private javax.swing.JButton btnRegistro_Julho;
    private javax.swing.JButton btnRegistro_Junho;
    private javax.swing.JButton btnRegistro_Maio;
    private javax.swing.JButton btnRegistro_Março;
    private javax.swing.JButton btnRegistro_Novembro;
    private javax.swing.JButton btnRegistro_Outubro;
    private javax.swing.JButton btnRegistro_Setembro;
    private javax.swing.JButton btn_Home_TelaInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
